### ISSUE TITLE
error al ejecutar mvn test

### ISSUE THREAD

**Issue by picardovidal** [dds-jv/foro#8]
👋 Hola, estoy teniendo el siguiente problema:
cree un nuevo proyecto con Maven  en Eclipse, agregue una nueva clase y un test para la misma.
Cuando corro los test manualmente, pasan ok, pero al ejecutar **mvn test** me da el siguiente error

> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE!
TestDummyDesign.testIntegrante5()  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/junit/Assert
	at TestDummyDesign.testIntegrante5(TestDummyDesign.java:10)
Caused by: java.lang.ClassNotFoundException: org.junit.Assert
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

la version de JDK que estoy utilizando es **jdk1.8.0_221** y la version de JUnit es **4.13.0**

por el error, no esta encontrando la clase assert, alguna idea de si hay algo extra que deba configurar

**Comment by picardovidal** [comment]
Ya encontre el problema, dejo la solución por aquí, por si le sirve a alguien mas.

El problema era, que faltaba la dependencia en el archivo pom.xml
agregue el siguiente código y ya esta funcionando correctamente.

> <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

saludos.
